version: 2
jobs:
  build:
    docker:
      - image: comum/docker-build-env:latest
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.05.0-ce
      # build the application container
      - run: apk add --update ca-certificates openssl && update-ca-certificates

      - run: docker build -t comum/payment-service:latest .
      - run: docker run -e POSTGRES_DB=services_core_test --name pg_default -p 5432:5432 -d postgres:9.6

      - run: docker run -i --rm --link pg_default:pg_default comum/services-core psql -U postgres -h pg_default -p 5432 services_core_test < init.sql
      - run: docker run -i --rm --link pg_default:pg_default comum/services-core psql -U postgres -h pg_default -p 5432 -c "alter user postgrest with superuser;"
      - run: docker run -i --rm --link pg_default:pg_default -e="DATABASE_URL=postgres://postgres@pg_default:5432/services_core_test" comum/services-core ./scripts/run_migrations.sh

      - run: docker run -i --rm --link pg_default:pg_default -e="DATABASE_URL=postgres://postgres@pg_default:5432/services_core_test" comum/payment-service npm test -- -v

  push_image:
    docker:
      - image: comum/docker-build-env:latest
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.05.0-ce
      # with credentials stored in the UI
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      # build the application container
      - run: docker build -t comum/payment-service:latest .
      # deploy the container
      - run: docker push comum/payment-service:latest

  deploy_production:
    docker:
      - image: comum/docker-build-env:latest
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.05.0-ce
      - run: apk update && apk add git nodejs nodejs-npm bash
      - run: npm install -g heroku-cli
      - run: docker build -t comum/payment-service:latest .
      - run: bash .circleci/setup-heroku.sh

      - run: heroku container:login
      - run: heroku container:push payment_stream_processor --recursive -a $PRODUCTION_PAYMENT_STREAM_APP
      - run: heroku container:push subscriptions_scheduler --recursive -a $PRODUCTION_SUBSCRIPTION_SCHEDULER_APP
      - run: heroku container:release payment_stream_processor -a $PRODUCTION_PAYMENT_STREAM_APP
      - run: heroku container:release subscriptions_scheduler -a $PRODUCTION_SUBSCRIPTION_SCHEDULER_APP

  deploy_sandbox:
    docker:
      - image: comum/docker-build-env:latest
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.05.0-ce
      - run: apk update && apk add git nodejs nodejs-npm bash
      - run: npm install -g heroku-cli
      - run: docker build -t comum/payment-service:latest .
      - run: bash .circleci/setup-heroku.sh

      - run: heroku container:login
      - run: heroku container:push payment_stream_processor --recursive -a $SANDBOX_PAYMENT_STREAM_APP
      - run: heroku container:push subscriptions_scheduler --recursive -a $SANDBOX_SUBSCRIPTION_SCHEDULER_APP
      - run: heroku container:release payment_stream_processor -a $SANDBOX_PAYMENT_STREAM_APP
      - run: heroku container:release subscriptions_scheduler -a $SANDBOX_SUBSCRIPTION_SCHEDULER_APP


workflows:
  version: 2
  build-and-push:
    jobs:
      - build
      - push_image:
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy_sandbox:
          requires:
            - build
          filters:
            branches:
              only: develop
      - deploy_production:
          requires:
            - build
          filters:
            branches:
              only: master
